application: tag-trading
version: 1
runtime: python
api_version: 1

handlers:
- url: /js/(.*)
  static_files: static/js/\1
  upload: static/js/.*.js
- url: /cron_jobs/.*
  script: cron.py
- url: /tasks/.*
  script: tasks.py
- url: .*
  script: main.py
